# Generated by Django 3.1.2 on 2020-10-27 23:24

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('reserved_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('RESERVED', 'RESERVED')], max_length=8)),
                ('minutes_estimated', models.IntegerField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(1)])),
                ('current_time', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 24, 37, 540876, tzinfo=utc))),
            ],
        ),
    ]
