# Generated by Django 3.1.2 on 2020-10-27 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 25, 30, 649332, tzinfo=utc)),
        ),
    ]
