# Generated by Django 3.1.2 on 2020-10-27 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date',
            new_name='reserv_date',
        ),
        migrations.AlterField(
            model_name='room',
            name='current_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 27, 22, 32, 55, 516915, tzinfo=utc)),
        ),
    ]
