# Generated by Django 3.1.2 on 2020-10-27 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201027_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='reserv_date',
            new_name='reserved_date',
        ),
        migrations.AlterField(
            model_name='room',
            name='current_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 27, 22, 36, 8, 575392, tzinfo=utc)),
        ),
    ]
